from dotenv import load_dotenv
import os
load_dotenv()

import mysql.connector

db = mysql.connector.connect(
    host=os.getenv("MYSQL_HOST", "localhost"),
    user=os.getenv("MYSQL_USER", "root"),
    password=os.getenv("MYSQL_PASSWORD", ""),
    database=os.getenv("MYSQL_DATABASE", "ai_ecommerce")
)

cursor = db.cursor()

products = [
    # ELECTRONICS
    ("Smartphone Gimbal", 5999, "Stabilizer for smooth smartphone videos", "Electronics"),
    ("Phone Camera Lens Kit", 1299, "Lens kit for smartphone photography", "Electronics"),
    ("MagSafe Phone Mount", 1499, "Magnetic mount for compatible smartphones", "Electronics"),
    ("Foldable Phone Stand", 499, "Foldable stand for smartphones", "Electronics"),
    ("Tablet Keyboard Case", 1999, "Keyboard case designed for tablets", "Electronics"),
    ("Tablet Screen Protector", 599, "Protective screen film for tablets", "Electronics"),
    ("Laptop Privacy Screen", 1499, "Privacy filter for laptop displays", "Electronics"),
    ("Laptop Docking Station", 4999, "Multi-port docking station for laptops", "Electronics"),
    ("Laptop Charger", 1999, "Replacement charger for compatible laptops", "Electronics"),
    ("Laptop Webcam Cover", 199, "Sliding privacy cover for webcams", "Electronics"),
    ("Ergonomic Mouse", 1499, "Comfortable ergonomic computer mouse", "Electronics"),
    ("Vertical Mouse", 1799, "Ergonomic vertical wireless mouse", "Electronics"),
    ("Numeric Keypad", 799, "Compact external numeric keypad", "Electronics"),
    ("Keyboard Wrist Rest", 599, "Comfortable wrist support for keyboards", "Electronics"),
    ("Gaming Mouse Pad", 899, "Large surface gaming mouse pad", "Electronics"),
    ("RGB Gaming Mouse Pad", 1299, "Gaming mouse pad with RGB lighting", "Electronics"),
    ("Gaming Keyboard", 2499, "Mechanical keyboard designed for gaming", "Electronics"),
    ("Gaming Monitor Stand", 1999, "Adjustable stand for computer monitors", "Electronics"),
    ("Monitor Light Bar", 2299, "LED light bar for computer monitors", "Electronics"),
    ("Monitor Privacy Filter", 1299, "Privacy filter for compatible monitors", "Electronics"),
    ("HDMI Switch", 999, "Switch between multiple HDMI devices", "Electronics"),
    ("DisplayPort Cable", 799, "High quality DisplayPort connection cable", "Electronics"),
    ("USB Extension Cable", 399, "Extended USB connection cable", "Electronics"),
    ("USB Ethernet Adapter", 899, "USB adapter for wired network connection", "Electronics"),
    ("USB Bluetooth Dongle", 499, "Bluetooth adapter for compatible computers", "Electronics"),
    ("Thunderbolt Cable", 1499, "High speed Thunderbolt connection cable", "Electronics"),
    ("USB C Dock", 2999, "Multi-port USB C docking device", "Electronics"),
    ("USB C Ethernet Hub", 1799, "USB C hub with Ethernet connectivity", "Electronics"),
    ("Wireless Charging Pad", 999, "Flat wireless charging pad", "Electronics"),
    ("Car Wireless Charger", 1799, "Wireless charging mount for cars", "Electronics"),
    ("Car Bluetooth Adapter", 799, "Bluetooth adapter for car audio systems", "Electronics"),
    ("FM Bluetooth Transmitter", 999, "Bluetooth transmitter for car audio", "Electronics"),
    ("Dash Camera", 3999, "Compact camera for vehicle recording", "Electronics"),
    ("Car Backup Camera", 2499, "Camera for vehicle reversing assistance", "Electronics"),
    ("Portable Power Station", 14999, "Portable rechargeable power station", "Electronics"),
    ("Solar Power Bank", 1999, "Portable power bank with solar charging support", "Electronics"),
    ("Battery Charger", 899, "Rechargeable battery charging device", "Electronics"),
    ("Rechargeable Batteries", 699, "Set of rechargeable batteries", "Electronics"),
    ("Smart LED Bulb", 799, "Connected LED bulb with smart controls", "Electronics"),
    ("RGB Smart Bulb", 999, "Color changing smart LED bulb", "Electronics"),
    ("Smart Light Switch", 1499, "Smart switch for compatible lighting", "Electronics"),
    ("Motion Sensor Light", 999, "Automatic light with motion detection", "Electronics"),
    ("LED Ceiling Light", 1799, "Energy efficient LED ceiling light", "Electronics"),
    ("LED Strip Controller", 599, "Controller for compatible LED strips", "Electronics"),
    ("Smart Temperature Sensor", 1299, "Digital temperature monitoring sensor", "Electronics"),
    ("Smart Motion Sensor", 1499, "Motion sensor for smart home systems", "Electronics"),
    ("Smart Smoke Detector", 2499, "Smart smoke detection device", "Electronics"),
    ("Smart Water Leak Sensor", 1799, "Sensor for detecting water leaks", "Electronics"),
    ("Smart Curtain Controller", 2999, "Controller for compatible motorized curtains", "Electronics"),
    ("Smart IR Remote", 1299, "Smart remote for compatible home devices", "Electronics"),
    ("Video Doorbell Chime", 999, "Wireless chime for compatible doorbells", "Electronics"),
    ("Indoor Security Camera", 2999, "Indoor camera for home monitoring", "Electronics"),
    ("Outdoor Security Camera", 3999, "Weather resistant security camera", "Electronics"),
    ("Baby Monitor", 3999, "Video monitor for baby rooms", "Electronics"),
    ("Digital Photo Frame", 2999, "Electronic frame for displaying photos", "Electronics"),
    ("Portable DAB Radio", 2499, "Compact digital radio receiver", "Electronics"),
    ("Clock Radio", 1499, "Digital clock combined with radio", "Electronics"),
    ("Electronic Kitchen Scale", 799, "Digital scale for kitchen measurements", "Electronics"),
    ("Digital Body Scale", 999, "Electronic scale for body weight", "Electronics"),
    ("Kitchen Timer", 399, "Digital timer for cooking", "Electronics"),
    ("Food Thermometer", 699, "Digital thermometer for food temperature", "Electronics"),
    ("Electric Milk Frother", 999, "Small electric milk frother", "Electronics"),
    ("Electric Coffee Grinder", 1999, "Electric grinder for coffee beans", "Electronics"),
    ("Electric Egg Boiler", 1299, "Automatic egg boiling appliance", "Electronics"),
    ("Toaster", 1799, "Electric toaster for everyday breakfast", "Electronics"),
    ("Sandwich Maker", 1999, "Electric sandwich making appliance", "Electronics"),
    ("Induction Cooktop", 2999, "Compact induction cooking appliance", "Electronics"),
    ("Electric Rice Cooker", 2499, "Automatic electric rice cooker", "Electronics"),
    ("Electric Chopper", 1499, "Compact electric food chopper", "Electronics"),
    ("Hand Blender", 1599, "Electric hand blender for food preparation", "Electronics"),
    ("Electric Juicer", 2499, "Electric juicer for fresh juice", "Electronics"),
    ("Air Fryer", 4999, "Hot air cooking appliance", "Electronics"),
    ("Room Heater", 2499, "Compact electric room heater", "Electronics"),
    ("Tower Fan", 3499, "Tall electric fan for room cooling", "Electronics"),
    ("Desk Humidifier", 1299, "Compact humidifier for indoor spaces", "Electronics"),
    ("Dehumidifier", 6999, "Home appliance for reducing indoor humidity", "Electronics"),
    ("Vacuum Robot", 14999, "Automatic robotic floor cleaning device", "Electronics"),
    ("Cordless Vacuum", 5999, "Rechargeable cordless vacuum cleaner", "Electronics"),
    ("Steam Iron", 1999, "Electric steam iron for clothes", "Electronics"),
    ("Garment Steamer", 2499, "Portable steamer for garments", "Electronics"),
    ("Electric Sewing Machine", 7999, "Compact electric sewing machine", "Electronics"),
    ("Digital Voice Recorder", 2499, "Portable digital audio recorder", "Electronics"),
    ("Portable Media Player", 1999, "Compact device for digital media playback", "Electronics"),
    ("Mini Hi-Fi System", 6999, "Compact home audio system", "Electronics"),
    ("Bookshelf Speakers", 4999, "Compact speakers for home audio", "Electronics"),
    ("Studio Headphone Stand", 999, "Desk stand for headphones", "Electronics"),
    ("Audio Mixer", 4999, "Compact mixer for audio equipment", "Electronics"),
    ("Karaoke Microphone", 1799, "Wireless microphone for karaoke", "Electronics"),

    # MENS
     ("Men Mandarin Collar Shirt", 1299, "Smart casual mandarin collar shirt", "Mens"),
    ("Men Oxford Shirt", 1499, "Classic Oxford cotton shirt", "Mens"),
    ("Men Chambray Shirt", 1399, "Lightweight chambray casual shirt", "Mens"),
    ("Men Flannel Shirt", 1299, "Warm checked flannel shirt", "Mens"),
    ("Men Hawaiian Shirt", 999, "Relaxed printed summer shirt", "Mens"),
    ("Men Henley Long Sleeve", 999, "Comfortable long sleeve henley", "Mens"),
    ("Men Raglan T-Shirt", 899, "Casual raglan sleeve t-shirt", "Mens"),
    ("Men Graphic Hoodie", 1299, "Casual graphic printed hoodie", "Mens"),
    ("Men Zip Hoodie", 1499, "Full zip casual hoodie", "Mens"),
    ("Men Pullover Sweater", 1599, "Warm pullover sweater", "Mens"),
    ("Men Cable Knit Sweater", 1799, "Textured cable knit sweater", "Mens"),
    ("Men Fleece Jacket", 1999, "Warm lightweight fleece jacket", "Mens"),
    ("Men Quilted Jacket", 2299, "Lightweight quilted winter jacket", "Mens"),
    ("Men Suede Jacket", 2999, "Classic suede style jacket", "Mens"),
    ("Men Parka", 2999, "Warm hooded winter parka", "Mens"),
    ("Men Raincoat", 1799, "Water resistant men's raincoat", "Mens"),
    ("Men Casual Blazer", 2499, "Smart casual blazer", "Mens"),
    ("Men Linen Blazer", 2699, "Lightweight linen blend blazer", "Mens"),
    ("Men Double Breasted Blazer", 2999, "Classic double breasted blazer", "Mens"),
    ("Men Formal Jacket", 2499, "Elegant formal jacket", "Mens"),
    ("Men Dress Pants", 1699, "Classic formal dress pants", "Mens"),
    ("Men Pleated Trousers", 1599, "Modern pleated trousers", "Mens"),
    ("Men Linen Pants", 1499, "Breathable linen pants", "Mens"),
    ("Men Twill Pants", 1399, "Durable cotton twill trousers", "Mens"),
    ("Men Utility Pants", 1599, "Practical utility trousers", "Mens"),
    ("Men Corduroy Trousers", 1699, "Soft corduroy trousers", "Mens"),
    ("Men Denim Overalls", 1999, "Casual denim overalls", "Mens"),
    ("Men Board Shorts", 899, "Comfortable shorts for beach and summer", "Mens"),
    ("Men Chino Shorts", 999, "Smart casual chino shorts", "Mens"),
    ("Men Linen Shorts", 999, "Lightweight linen shorts", "Mens"),
    ("Men Swimming Trunks", 1099, "Comfortable swimming trunks", "Mens"),
    ("Men Thermal Shirt", 899, "Warm thermal inner shirt", "Mens"),
    ("Men Thermal Leggings", 899, "Warm thermal inner leggings", "Mens"),
    ("Men Night Suit", 1299, "Comfortable men's night suit", "Mens"),
    ("Men Lounge Pants", 999, "Soft lounge pants for home", "Mens"),
    ("Men Bathrobe", 1599, "Soft cotton bathrobe", "Mens"),
    ("Men Cotton Shorts", 799, "Everyday cotton shorts", "Mens"),
    ("Men Athletic Shorts", 899, "Lightweight athletic shorts", "Mens"),
    ("Men Cycling Shorts", 999, "Stretch cycling shorts", "Mens"),
    ("Men Compression Shorts", 999, "Stretchable sports compression shorts", "Mens"),
    ("Men Tennis Shoes", 2499, "Shoes designed for tennis activities", "Mens"),
    ("Men Basketball Shoes", 2999, "Cushioned basketball footwear", "Mens"),
    ("Men Football Boots", 3499, "Sports footwear for football", "Mens"),
    ("Men Cricket Shoes", 2799, "Sports shoes for cricket", "Mens"),
    ("Men Trail Shoes", 2999, "Durable shoes for trail activities", "Mens"),
    ("Men Walking Shoes", 1999, "Comfortable shoes for daily walking", "Mens"),
    ("Men Boat Shoes", 1899, "Casual boat style footwear", "Mens"),
    ("Men Derby Shoes", 2299, "Classic formal Derby shoes", "Mens"),
    ("Men Monk Strap Shoes", 2499, "Formal monk strap footwear", "Mens"),
    ("Men Oxford Shoes", 2499, "Classic formal Oxford shoes", "Mens"),
    ("Men Moccasins", 1799, "Comfortable casual moccasin footwear", "Mens"),
    ("Men House Slippers", 599, "Soft indoor slippers", "Mens"),
    ("Men Hiking Sandals", 1299, "Outdoor sandals for hiking", "Mens"),
    ("Men Leather Boots", 2999, "Durable leather style boots", "Mens"),
    ("Men Ankle Boots", 2499, "Casual ankle boots", "Mens"),
    ("Men Cross Trainers", 2499, "Versatile training footwear", "Mens"),
    ("Men Gym Shoes", 2199, "Lightweight footwear for gym workouts", "Mens"),
    ("Men Running Vest", 799, "Lightweight sports running vest", "Mens"),
    ("Men Sports Polo", 999, "Breathable sports polo shirt", "Mens"),
    ("Men Gym T-Shirt", 799, "Moisture friendly gym t-shirt", "Mens"),
    ("Men Cycling Jersey", 1299, "Lightweight cycling jersey", "Mens"),
    ("Men Football Jersey", 1299, "Sports football jersey", "Mens"),
    ("Men Cricket Jersey", 1299, "Sports cricket jersey", "Mens"),
    ("Men Sports Socks", 499, "Comfortable athletic socks", "Mens"),
    ("Men Ankle Socks", 399, "Everyday ankle socks", "Mens"),
    ("Men Cotton Socks", 449, "Soft cotton everyday socks", "Mens"),
    ("Men Belt Bag", 899, "Compact waist belt bag", "Mens"),
    ("Men Laptop Bag", 1999, "Professional laptop carrying bag", "Mens"),
    ("Men Messenger Bag", 1499, "Everyday messenger shoulder bag", "Mens"),
    ("Men Waist Bag", 799, "Compact waist bag for travel", "Mens"),
    ("Men Travel Backpack", 2299, "Spacious backpack for travel", "Mens"),
    ("Men Gym Bag", 1399, "Sports bag for gym essentials", "Mens"),
    ("Men Toiletry Bag", 799, "Compact travel toiletry bag", "Mens"),
    ("Men Passport Holder", 599, "Travel passport holder", "Mens"),
    ("Men Key Holder", 399, "Compact key organizer", "Mens"),
    ("Men Watch Box", 1499, "Storage box for wrist watches", "Mens"),
    ("Men Tie Clip", 499, "Metal tie clip accessory", "Mens"),
    ("Men Bow Tie", 699, "Classic formal bow tie", "Mens"),
    ("Men Suspenders Set", 899, "Adjustable formal suspenders set", "Mens"),
    ("Men Winter Ear Warmers", 599, "Warm ear accessories for winter", "Mens"),
    ("Men Neck Gaiter", 499, "Lightweight neck gaiter", "Mens"),
    ("Men Sun Hat", 699, "Wide brim casual sun hat", "Mens"),
    ("Men Straw Hat", 799, "Lightweight straw summer hat", "Mens"),
    ("Men Sports Cap", 499, "Breathable sports cap", "Mens"),
    ("Men Leather Bracelet", 799, "Casual leather bracelet", "Mens"),
    ("Men Chain Bracelet", 999, "Simple metal chain bracelet", "Mens"),

    # WOMENS
    ("Women Henley Top", 799, "Comfortable casual henley top", "Womens"),
    ("Women V-Neck Top", 699, "Classic V-neck casual top", "Womens"),
    ("Women Halter Top", 899, "Stylish halter neck top", "Womens"),
    ("Women Off Shoulder Top", 999, "Trendy off shoulder top", "Womens"),
    ("Women Wrap Top", 1099, "Elegant wrap style top", "Womens"),
    ("Women Ruffle Top", 999, "Casual top with ruffle detailing", "Womens"),
    ("Women Embroidered Top", 1199, "Decorative embroidered casual top", "Womens"),
    ("Women Striped Shirt", 1099, "Classic striped casual shirt", "Womens"),
    ("Women Oversized Shirt", 1299, "Relaxed oversized shirt", "Womens"),
    ("Women Flannel Shirt", 1199, "Soft checked flannel shirt", "Womens"),
    ("Women Chambray Shirt", 1299, "Lightweight chambray shirt", "Womens"),
    ("Women Peasant Blouse", 1099, "Relaxed peasant style blouse", "Womens"),
    ("Women Wrap Blouse", 1199, "Elegant wrap style blouse", "Womens"),
    ("Women Embroidered Blouse", 1399, "Detailed embroidered blouse", "Womens"),
    ("Women Pleated Blouse", 1299, "Smart pleated blouse", "Womens"),
    ("Women Knit Sweater", 1499, "Soft knitted sweater", "Womens"),
    ("Women Cable Knit Sweater", 1699, "Warm cable knit sweater", "Womens"),
    ("Women Turtleneck Sweater", 1599, "Warm turtleneck sweater", "Womens"),
    ("Women Knit Vest", 999, "Sleeveless knitted vest", "Womens"),
    ("Women Fleece Jacket", 1999, "Warm lightweight fleece jacket", "Womens"),
    ("Women Quilted Jacket", 2299, "Lightweight quilted jacket", "Womens"),
    ("Women Bomber Jacket", 2199, "Casual bomber jacket", "Womens"),
    ("Women Suede Jacket", 2999, "Classic suede style jacket", "Womens"),
    ("Women Parka", 2999, "Warm hooded winter parka", "Womens"),
    ("Women Cape Coat", 2799, "Elegant cape style coat", "Womens"),
    ("Women Long Coat", 2999, "Classic long winter coat", "Womens"),
    ("Women Formal Blazer", 2499, "Smart formal blazer", "Womens"),
    ("Women Linen Blazer", 2699, "Lightweight linen blend blazer", "Womens"),
    ("Women Pleated Pants", 1499, "Modern pleated trousers", "Womens"),
    ("Women Straight Pants", 1399, "Classic straight fit trousers", "Womens"),
    ("Women Flared Pants", 1499, "Stylish flared trousers", "Womens"),
    ("Women Ankle Pants", 1299, "Smart ankle length trousers", "Womens"),
    ("Women Linen Trousers", 1599, "Breathable linen trousers", "Womens"),
    ("Women Track Pants", 1199, "Comfortable athletic track pants", "Womens"),
    ("Women Denim Overalls", 1899, "Casual denim overalls", "Womens"),
    ("Women Dungarees", 1799, "Casual dungaree outfit", "Womens"),
    ("Women Bermuda Shorts", 999, "Comfortable casual Bermuda shorts", "Womens"),
    ("Women Denim Shorts", 999, "Casual denim shorts", "Womens"),
    ("Women Linen Shorts", 999, "Lightweight linen shorts", "Womens"),
    ("Women Biker Shorts", 799, "Stretchable casual biker shorts", "Womens"),
    ("Women Cycling Shorts", 899, "Stretch cycling shorts", "Womens"),
    ("Women Jumpsuit Dress", 1999, "Stylish one piece jumpsuit dress", "Womens"),
    ("Women Shirt Dress", 1699, "Smart casual shirt dress", "Womens"),
    ("Women Wrap Dress", 1799, "Elegant wrap style dress", "Womens"),
    ("Women A-Line Dress", 1599, "Classic A-line casual dress", "Womens"),
    ("Women Bodycon Dress", 1699, "Modern fitted style dress", "Womens"),
    ("Women Pleated Dress", 1799, "Elegant pleated dress", "Womens"),
    ("Women Tiered Dress", 1599, "Flowing tiered casual dress", "Womens"),
    ("Women Sweater Dress", 1899, "Warm knitted sweater dress", "Womens"),
    ("Women Cocktail Dress", 2299, "Elegant occasion dress", "Womens"),
    ("Women Evening Dress", 2499, "Elegant evening wear dress", "Womens"),
    ("Women Tennis Skirt", 999, "Pleated sports style skirt", "Womens"),
    ("Women Denim Skirt", 1199, "Casual denim skirt", "Womens"),
    ("Women Pleated Skirt", 1299, "Classic pleated skirt", "Womens"),
    ("Women Maxi Skirt", 1399, "Flowing long maxi skirt", "Womens"),
    ("Women Wrap Skirt", 1199, "Stylish wrap skirt", "Womens"),
    ("Women Pencil Skirt", 1299, "Classic formal pencil skirt", "Womens"),
    ("Women Tennis Shoes", 2299, "Comfortable shoes for tennis", "Womens"),
    ("Women Basketball Shoes", 2499, "Cushioned basketball footwear", "Womens"),
    ("Women Walking Shoes", 1899, "Comfortable everyday walking shoes", "Womens"),
    ("Women Hiking Shoes", 2799, "Durable outdoor hiking footwear", "Womens"),
    ("Women Trail Shoes", 2699, "Outdoor trail footwear", "Womens"),
    ("Women Mules", 1799, "Stylish slip-on mule footwear", "Womens"),
    ("Women Espadrilles", 1599, "Casual espadrille footwear", "Womens"),
    ("Women Wedges", 1999, "Comfortable wedge footwear", "Womens"),
    ("Women Ballet Flats", 1299, "Classic flat footwear", "Womens"),
    ("Women Platform Sandals", 1599, "Modern platform sandals", "Womens"),
    ("Women Ankle Boots", 2499, "Casual ankle boots", "Womens"),
    ("Women Knee Boots", 2999, "Stylish knee high boots", "Womens"),
    ("Women Tote Purse", 1499, "Spacious everyday purse", "Womens"),
    ("Women Mini Bag", 999, "Compact fashion bag", "Womens"),
    ("Women Bucket Bag", 1399, "Stylish bucket shaped bag", "Womens"),
    ("Women Waist Bag", 899, "Compact waist bag", "Womens"),
    ("Women Travel Backpack", 1999, "Spacious backpack for travel", "Womens"),
    ("Women Laptop Bag", 1999, "Professional laptop carrying bag", "Womens"),
    ("Women Cosmetic Bag", 699, "Compact bag for cosmetics", "Womens"),
    ("Women Passport Holder", 599, "Travel passport holder", "Womens"),
    ("Women Coin Purse", 499, "Small coin storage purse", "Womens"),
    ("Women Brooch", 599, "Decorative fashion brooch", "Womens"),
    ("Women Hair Claw Set", 399, "Set of decorative hair claws", "Womens"),
    ("Women Hair Clip Set", 399, "Set of stylish hair clips", "Womens"),
    ("Women Headband", 499, "Comfortable fashion headband", "Womens"),
    ("Women Leg Warmers", 699, "Warm knitted leg warmers", "Womens"),
    ("Women Fashion Tights", 599, "Comfortable fashion tights", "Womens"),

    # KIDS
    ("Kids Henley T-Shirt", 699, "Comfortable henley t-shirt for kids", "Kids"),
    ("Kids V-Neck T-Shirt", 599, "Soft V-neck t-shirt for kids", "Kids"),
    ("Kids Graphic Hoodie", 899, "Fun graphic printed hoodie", "Kids"),
    ("Kids Zip Hoodie", 999, "Comfortable zip-up hoodie", "Kids"),
    ("Kids Knit Sweater", 999, "Warm knitted sweater for children", "Kids"),
    ("Kids Cable Knit Sweater", 1199, "Warm cable knit sweater", "Kids"),
    ("Kids Fleece Jacket", 1299, "Soft lightweight fleece jacket", "Kids"),
    ("Kids Quilted Jacket", 1499, "Warm quilted winter jacket", "Kids"),
    ("Kids Puffer Vest", 1199, "Warm sleeveless winter vest", "Kids"),
    ("Kids Windcheater Jacket", 1199, "Lightweight wind protection jacket", "Kids"),
    ("Kids Party Shirt", 799, "Smart shirt for special occasions", "Kids"),
    ("Kids Formal Shirt", 899, "Smart formal shirt for children", "Kids"),
    ("Kids Striped Shirt", 699, "Casual striped shirt", "Kids"),
    ("Kids Checked Shirt", 699, "Classic checked casual shirt", "Kids"),
    ("Kids Denim Overalls", 1299, "Casual denim overalls", "Kids"),
    ("Kids Dungarees", 1199, "Comfortable denim dungarees", "Kids"),
    ("Kids Chinos", 899, "Smart casual chinos for children", "Kids"),
    ("Kids Cotton Trousers", 799, "Soft cotton trousers", "Kids"),
    ("Kids Denim Shorts", 699, "Casual denim shorts", "Kids"),
    ("Kids Cargo Shorts", 699, "Utility style cargo shorts", "Kids"),
    ("Kids Bermuda Shorts", 699, "Comfortable Bermuda shorts", "Kids"),
    ("Kids Sports Pants", 799, "Comfortable sports pants", "Kids"),
    ("Kids Thermal Shirt", 699, "Warm thermal inner shirt", "Kids"),
    ("Kids Thermal Pants", 699, "Warm thermal inner pants", "Kids"),
    ("Kids Night Dress", 799, "Comfortable night dress", "Kids"),
    ("Kids Lounge Set", 899, "Soft matching lounge set", "Kids"),
    ("Kids Party Frock", 1299, "Festive frock for special occasions", "Kids"),
    ("Kids Floral Dress", 999, "Colorful floral casual dress", "Kids"),
    ("Kids Denim Dress", 1099, "Casual denim dress", "Kids"),
    ("Kids Tutu Dress", 1199, "Fun tutu style dress", "Kids"),
    ("Kids Jumpsuit", 999, "Comfortable children's jumpsuit", "Kids"),
    ("Kids Romper", 799, "Soft everyday romper", "Kids"),
    ("Kids Summer Dress", 899, "Lightweight summer dress", "Kids"),
    ("Kids Winter Dress", 1199, "Warm winter dress", "Kids"),
    ("Kids Pleated Skirt", 799, "Smart pleated skirt", "Kids"),
    ("Kids Denim Skirt", 799, "Casual denim skirt", "Kids"),
    ("Kids Sports Skirt", 699, "Comfortable sports skirt", "Kids"),
    ("Kids Cotton Leggings", 599, "Soft stretch cotton leggings", "Kids"),
    ("Kids Sports Leggings", 699, "Stretchable sports leggings", "Kids"),
    ("Kids Track Pants", 699, "Comfortable track pants", "Kids"),
    ("Kids Football Boots", 1499, "Sports boots for football", "Kids"),
    ("Kids Cricket Shoes", 1299, "Sports shoes for cricket", "Kids"),
    ("Kids Tennis Shoes", 1299, "Comfortable tennis footwear", "Kids"),
    ("Kids Basketball Shoes", 1499, "Cushioned basketball shoes", "Kids"),
    ("Kids Walking Shoes", 999, "Comfortable daily walking shoes", "Kids"),
    ("Kids Canvas Shoes", 799, "Casual canvas footwear", "Kids"),
    ("Kids Ballet Shoes", 899, "Lightweight ballet style shoes", "Kids"),
    ("Kids Party Sandals", 799, "Smart sandals for occasions", "Kids"),
    ("Kids Sports Sandals", 699, "Comfortable sports sandals", "Kids"),
    ("Kids Rain Sandals", 599, "Water friendly sandals", "Kids"),
    ("Kids Winter Boots", 1299, "Warm winter footwear", "Kids"),
    ("Kids Ankle Boots", 1199, "Casual ankle boots", "Kids"),
    ("Kids Slipper Shoes", 599, "Soft indoor slipper shoes", "Kids"),
    ("Kids School Backpack", 1299, "Durable backpack for school", "Kids"),
    ("Kids Trolley Bag", 1999, "Small trolley bag for children", "Kids"),
    ("Kids Crossbody Bag", 699, "Small crossbody bag for kids", "Kids"),
    ("Kids Pencil Pouch", 299, "Compact school pencil pouch", "Kids"),
    ("Kids Art Bag", 499, "Small bag for art supplies", "Kids"),
    ("Kids Snack Box", 499, "Reusable snack storage box", "Kids"),
    ("Kids Lunch Box", 599, "School lunch storage box", "Kids"),
    ("Kids Insulated Bottle", 699, "Insulated reusable water bottle", "Kids"),
    ("Kids Sports Bottle", 499, "Reusable bottle for sports activities", "Kids"),
    ("Kids Travel Bottle", 399, "Compact bottle for travel", "Kids"),
    ("Kids Sun Hat", 499, "Lightweight hat for sunny days", "Kids"),
    ("Kids Bucket Hat", 499, "Casual bucket hat for children", "Kids"),
    ("Kids Baseball Cap", 399, "Casual children's baseball cap", "Kids"),
    ("Kids Winter Beanie", 499, "Warm knitted winter beanie", "Kids"),
    ("Kids Winter Muffler", 599, "Warm winter muffler", "Kids"),
    ("Kids Thermal Gloves", 399, "Warm thermal gloves", "Kids"),
    ("Kids Knee Socks", 399, "Comfortable knee length socks", "Kids"),
    ("Kids Ankle Socks", 299, "Soft ankle socks", "Kids"),
    ("Kids Sports Socks", 349, "Comfortable sports socks", "Kids"),
    ("Kids Cotton Underwear Set", 499, "Soft cotton underwear set", "Kids"),
    ("Kids Thermal Underwear", 699, "Warm thermal underwear", "Kids"),
    ("Kids Swim Cap", 299, "Comfortable swim cap", "Kids"),
    ("Kids Swimming Goggles", 499, "Protective swimming goggles", "Kids"),
    ("Kids Swim Shorts", 699, "Comfortable swim shorts", "Kids"),
    ("Kids Beach Towel", 599, "Soft towel for beach and swimming", "Kids"),
    ("Kids Sleeping Robe", 999, "Soft robe for bedtime", "Kids"),
    ("Kids Dressing Gown", 999, "Comfortable children's dressing gown", "Kids"),
    ("Kids Activity Apron", 399, "Protective apron for activities", "Kids"),
    ("Kids Art Smock", 499, "Protective smock for art activities", "Kids"),
    ("Kids Travel Blanket", 799, "Soft blanket for travel", "Kids"),

    # MAKEUP
    ("Hydrating Skin Primer", 899, "Hydrating primer for a smooth makeup base", "Makeup"),
    ("Pore Minimizing Primer", 999, "Primer designed for a smooth looking base", "Makeup"),
    ("Illuminating Primer", 999, "Primer with a subtle illuminating finish", "Makeup"),
    ("Mattifying Primer", 899, "Lightweight primer with a matte finish", "Makeup"),
    ("Foundation Stick", 899, "Easy to blend foundation stick", "Makeup"),
    ("Serum Concealer", 799, "Lightweight serum texture concealer", "Makeup"),
    ("Full Coverage Concealer", 899, "Buildable full coverage concealer", "Makeup"),
    ("Color Correcting Palette", 999, "Multi shade correcting palette", "Makeup"),
    ("Banana Powder", 699, "Yellow toned setting powder", "Makeup"),
    ("Finishing Powder", 799, "Lightweight powder for finishing makeup", "Makeup"),
    ("Pressed Setting Powder", 699, "Pressed powder for setting makeup", "Makeup"),
    ("Cream Contour", 799, "Blendable cream contour product", "Makeup"),
    ("Liquid Contour", 899, "Liquid contour for facial definition", "Makeup"),
    ("Contour Powder", 699, "Powder contour for face definition", "Makeup"),
    ("Cream Bronzer Stick", 899, "Easy blend bronzer stick", "Makeup"),
    ("Liquid Bronzer", 899, "Buildable liquid bronzer", "Makeup"),
    ("Shimmer Bronzer", 799, "Bronzer with a subtle shimmer finish", "Makeup"),
    ("Cream Highlighter Stick", 799, "Cream highlighter in stick format", "Makeup"),
    ("Highlighter Duo", 899, "Two shade face highlighter duo", "Makeup"),
    ("Highlighter Palette", 1199, "Multi shade face highlighter palette", "Makeup"),
    ("Liquid Blush", 699, "Lightweight liquid blush", "Makeup"),
    ("Blush Duo", 799, "Two shade blush palette", "Makeup"),
    ("Blush Palette", 999, "Multi shade blush palette", "Makeup"),
    ("Cream Eyeshadow", 599, "Easy blend cream eyeshadow", "Makeup"),
    ("Eyeshadow Stick", 599, "Convenient eyeshadow stick", "Makeup"),
    ("Eyeshadow Duo", 499, "Two shade eyeshadow duo", "Makeup"),
    ("Pastel Eyeshadow Palette", 999, "Soft pastel shade eyeshadow palette", "Makeup"),
    ("Warm Tone Eyeshadow Palette", 1099, "Warm shade eyeshadow palette", "Makeup"),
    ("Cool Tone Eyeshadow Palette", 1099, "Cool shade eyeshadow palette", "Makeup"),
    ("Metallic Eyeshadow", 499, "Metallic finish single eyeshadow", "Makeup"),
    ("Matte Eyeshadow", 499, "Matte finish single eyeshadow", "Makeup"),
    ("Eyeshadow Primer", 599, "Primer designed for eye makeup", "Makeup"),
    ("Eyeliner Pencil", 399, "Classic pencil eyeliner", "Makeup"),
    ("Felt Tip Eyeliner", 499, "Easy application felt tip eyeliner", "Makeup"),
    ("Eyeliner Pen", 499, "Precision liquid eyeliner pen", "Makeup"),
    ("Kohl Pencil", 399, "Smooth kohl eye pencil", "Makeup"),
    ("Colored Kajal", 449, "Colored kajal eye pencil", "Makeup"),
    ("Waterproof Mascara", 699, "Water resistant everyday mascara", "Makeup"),
    ("Curling Mascara", 699, "Mascara designed to enhance lash curl", "Makeup"),
    ("Lash Primer", 599, "Primer for enhancing mascara application", "Makeup"),
    ("Clear Brow Gel", 499, "Transparent brow styling gel", "Makeup"),
    ("Tinted Brow Gel", 599, "Tinted gel for eyebrow definition", "Makeup"),
    ("Brow Pomade", 699, "Creamy brow pomade for definition", "Makeup"),
    ("Brow Powder Duo", 699, "Two shade eyebrow powder duo", "Makeup"),
    ("Lip Primer", 499, "Smooth base for lip makeup", "Makeup"),
    ("Lip Mask", 599, "Moisturizing lip treatment mask", "Makeup"),
    ("Lip Oil", 699, "Lightweight glossy lip oil", "Makeup"),
    ("Lip Serum", 799, "Hydrating serum for lips", "Makeup"),
    ("Lip Butter", 499, "Soft moisturizing lip butter", "Makeup"),
    ("Cream Lip Tint", 599, "Creamy tinted lip color", "Makeup"),
    ("Water Tint", 599, "Lightweight water based lip tint", "Makeup"),
    ("Glossy Lip Tint", 699, "Lip tint with glossy finish", "Makeup"),
    ("Velvet Lip Color", 699, "Soft velvet finish lip color", "Makeup"),
    ("Lipstick Crayon Set", 899, "Set of creamy lipstick crayons", "Makeup"),
    ("Matte Lip Crayon", 599, "Matte finish lip crayon", "Makeup"),
    ("Lip Liner Pencil Set", 799, "Set of lip liner pencils", "Makeup"),
    ("Nude Lip Palette", 999, "Multi shade nude lip palette", "Makeup"),
    ("Makeup Brush Kit", 1299, "Complete set of makeup brushes", "Makeup"),
    ("Kabuki Brush", 699, "Dense brush for face makeup", "Makeup"),
    ("Fan Brush", 499, "Fan shaped brush for highlighter", "Makeup"),
    ("Angled Brush", 399, "Angled brush for detailed makeup", "Makeup"),
    ("Detail Makeup Brush", 399, "Small brush for precise application", "Makeup"),
    ("Lip Brush", 399, "Small brush for lip application", "Makeup"),
    ("Brow Brush", 399, "Angled brush for eyebrow makeup", "Makeup"),
    ("Eyeliner Brush", 399, "Fine brush for eyeliner application", "Makeup"),
    ("Makeup Puff Set", 499, "Set of soft makeup puffs", "Makeup"),
    ("Powder Puff", 299, "Soft puff for powder application", "Makeup"),
    ("Silicone Makeup Sponge", 399, "Reusable silicone makeup applicator", "Makeup"),
    ("Blending Sponge Set", 599, "Set of makeup blending sponges", "Makeup"),
    ("Makeup Mixing Palette", 499, "Palette for mixing makeup products", "Makeup"),
    ("Makeup Spatula", 299, "Small spatula for makeup application", "Makeup"),
    ("Brush Drying Rack", 799, "Rack for drying makeup brushes", "Makeup"),
    ("Brush Storage Case", 899, "Protective case for makeup brushes", "Makeup"),
    ("Travel Makeup Case", 1499, "Compact case for carrying makeup", "Makeup"),
    ("Makeup Train Case", 1999, "Organized storage case for cosmetics", "Makeup"),
    ("Portable Makeup Mirror", 899, "Compact mirror for makeup application", "Makeup"),
    ("LED Makeup Mirror", 1999, "Makeup mirror with LED lighting", "Makeup"),
    ("Compact Vanity Mirror", 799, "Small tabletop vanity mirror", "Makeup"),
    ("Makeup Cleaning Mat", 399, "Silicone mat for cleaning brushes", "Makeup"),
    ("Eyelash Separator", 299, "Tool for separating eyelashes", "Makeup"),
    ("False Lash Applicator", 399, "Tool for applying false eyelashes", "Makeup"),
    ("Reusable False Lashes", 599, "Reusable false eyelashes", "Makeup"),
    ("Individual Lashes", 499, "Individual lashes for custom looks", "Makeup"),
    ("Nail Art Stickers", 299, "Decorative stickers for nail designs", "Makeup"),
    ("Nail Art Brush Set", 499, "Fine brushes for nail art", "Makeup"),


    # GROCERY
    ("Basmati Rice Premium", 899, "Premium long grain basmati rice", "Grocery"),
    ("Organic Brown Rice", 249, "Organic whole grain brown rice", "Grocery"),
    ("Red Rice", 199, "Nutritious red rice", "Grocery"),
    ("Black Rice", 299, "Premium black rice", "Grocery"),
    ("Idli Rice", 149, "Rice suitable for soft idlis", "Grocery"),
    ("Rice Flour Fine", 119, "Fine ground rice flour", "Grocery"),
    ("Whole Wheat Atta", 299, "Fresh whole wheat flour", "Grocery"),
    ("Chakki Atta", 349, "Stone ground wheat flour", "Grocery"),
    ("Jowar Flour", 149, "Nutritious sorghum flour", "Grocery"),
    ("Bajra Flour", 139, "Fresh pearl millet flour", "Grocery"),
    ("Maida", 99, "Refined wheat flour", "Grocery"),
    ("Sattu", 129, "Roasted gram flour", "Grocery"),
    ("Arrowroot Powder", 149, "Fine arrowroot starch powder", "Grocery"),
    ("Buckwheat Flour", 199, "Gluten free buckwheat flour", "Grocery"),
    ("Chia Seeds", 249, "Nutrient rich chia seeds", "Grocery"),
    ("Flax Seeds", 179, "Natural flax seeds", "Grocery"),
    ("Pumpkin Seeds", 299, "Roasted pumpkin seeds", "Grocery"),
    ("Sunflower Seeds", 229, "Crunchy sunflower seeds", "Grocery"),
    ("Sesame Seeds", 149, "Natural sesame seeds", "Grocery"),
    ("Hemp Seeds", 399, "Nutrient rich hemp seeds", "Grocery"),
    ("Green Moong Whole", 149, "Whole green moong beans", "Grocery"),
    ("Moth Beans", 139, "Protein rich moth beans", "Grocery"),
    ("Horse Gram", 129, "Nutritious horse gram", "Grocery"),
    ("Arhar Dal Premium", 199, "Premium split pigeon peas", "Grocery"),
    ("Masoor Whole", 139, "Whole red lentils", "Grocery"),
    ("Urad Whole", 159, "Whole black gram", "Grocery"),
    ("Lobia", 149, "Fresh black eyed beans", "Grocery"),
    ("Soybean", 129, "Protein rich soybeans", "Grocery"),
    ("Dried Green Peas", 149, "Dried green peas", "Grocery"),
    ("Dried White Peas", 159, "Dried white peas", "Grocery"),
    ("Pinto Beans", 249, "Nutritious dried pinto beans", "Grocery"),
    ("Chaat Masala", 89, "Tangy spice blend for snacks", "Grocery"),
    ("Kitchen King Masala", 99, "Aromatic mixed spice blend", "Grocery"),
    ("Pav Bhaji Masala", 89, "Spice blend for pav bhaji", "Grocery"),
    ("Chole Masala", 89, "Spice blend for chickpea curry", "Grocery"),
    ("Biryani Masala", 119, "Aromatic biryani spice blend", "Grocery"),
    ("Chicken Masala", 109, "Spiced seasoning mix", "Grocery"),
    ("Curry Powder", 109, "Balanced curry spice blend", "Grocery"),
    ("Ginger Garlic Paste", 99, "Ready to use ginger garlic paste", "Grocery"),
    ("Green Chilli Sauce", 129, "Spicy green chilli sauce", "Grocery"),
    ("Red Chilli Sauce", 129, "Tangy red chilli sauce", "Grocery"),
    ("Soy Sauce", 119, "Classic dark soy sauce", "Grocery"),
    ("Chilli Garlic Sauce", 149, "Spicy chilli garlic sauce", "Grocery"),
    ("Pasta Sauce", 179, "Rich tomato pasta sauce", "Grocery"),
    ("Pizza Sauce", 169, "Seasoned tomato pizza sauce", "Grocery"),
    ("Tomato Puree", 99, "Smooth tomato puree", "Grocery"),
    ("Green Chutney", 89, "Ready to use green chutney", "Grocery"),
    ("Tamarind Chutney", 99, "Sweet and tangy tamarind chutney", "Grocery"),
    ("Mango Pickle", 149, "Traditional spicy mango pickle", "Grocery"),
    ("Lemon Pickle", 139, "Tangy lemon pickle", "Grocery"),
    ("Mixed Vegetable Pickle", 159, "Traditional mixed vegetable pickle", "Grocery"),
    ("Apple Cider Vinegar", 249, "Apple cider vinegar", "Grocery"),
    ("White Vinegar", 79, "Multipurpose white vinegar", "Grocery"),
    ("Baking Soda", 69, "Food grade baking soda", "Grocery"),
    ("Baking Powder", 89, "Raising agent for baking", "Grocery"),
    ("Vanilla Essence", 119, "Vanilla flavoring for baking", "Grocery"),
    ("Cornflakes Choco", 249, "Chocolate flavored breakfast cereal", "Grocery"),
    ("Honey Granola", 299, "Crunchy granola with honey", "Grocery"),
    ("Fruit Granola", 329, "Granola with dried fruit", "Grocery"),
    ("Instant Oatmeal", 179, "Quick preparation oatmeal", "Grocery"),
    ("Peanut Chikki", 119, "Traditional peanut brittle snack", "Grocery"),
    ("Roasted Makhana", 199, "Crunchy roasted fox nuts", "Grocery"),
    ("Masala Makhana", 229, "Spiced roasted fox nuts", "Grocery"),
    ("Roasted Almonds", 399, "Crunchy roasted almonds", "Grocery"),
    ("Cashew Pieces", 449, "Premium cashew pieces", "Grocery"),
    ("Pistachio Kernels", 499, "Premium shelled pistachios", "Grocery"),
    ("Walnut Kernels", 499, "Premium walnut kernels", "Grocery"),
    ("Raisins Golden", 249, "Sweet golden raisins", "Grocery"),
    ("Dates Seedless", 299, "Soft seedless dates", "Grocery"),
    ("Dried Cranberries", 349, "Sweet dried cranberries", "Grocery"),
    ("Dried Figs", 399, "Naturally dried figs", "Grocery"),
    ("Trail Mix", 349, "Mixed nuts and dried fruits", "Grocery"),
    ("Salted Peanuts", 99, "Crunchy salted peanuts", "Grocery"),
    ("Roasted Chana", 99, "Crunchy roasted gram snack", "Grocery"),
    ("Masala Peanuts", 119, "Spicy roasted peanut snack", "Grocery"),
    ("Nacho Chips", 129, "Crunchy nacho style chips", "Grocery"),
    ("Cheese Crackers", 149, "Crunchy cheese flavored crackers", "Grocery"),
    ("Cream Biscuits", 99, "Sweet cream filled biscuits", "Grocery"),
    ("Digestive Biscuits", 119, "Crunchy digestive biscuits", "Grocery"),
    ("Dark Chocolate Bar", 199, "Rich dark chocolate bar", "Grocery"),
    ("Milk Chocolate Bar", 149, "Smooth milk chocolate bar", "Grocery"),
    ("White Chocolate Bar", 179, "Creamy white chocolate bar", "Grocery"),
    ("Peanut Choco Spread", 299, "Chocolate peanut spread", "Grocery"),
    ("Strawberry Preserve", 199, "Sweet strawberry fruit preserve", "Grocery"),
    ("Orange Marmalade", 199, "Citrus orange marmalade", "Grocery"),
    ("Maple Syrup", 399, "Sweet maple syrup", "Grocery"),
]

for product in products:
    cursor.execute("""
        INSERT INTO products
        (name, price, description, category, image)
        VALUES (%s, %s, %s, %s, %s)
    """, (
        product[0],
        product[1],
        product[2],
        product[3],
        ""
    ))

db.commit()

print(len(products), "products added successfully!")

cursor.close()
db.close()